[package]
name = "elp"
version = "0.99.0"
authors = ["Eric D. Reichert <eric@reichertconsulting.com>"]
description = "AWS ELB Access Log Parser"


[dependencies]
walkdir = "0.1.5"
chrono = "0.2.19"
log = "0.3.5"
