[package]
name = "aws-abacus"
version = "0.1.0"
authors = ["Eric D. Reichert <eric@reichertconsulting.com>"]

[dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
walkdir = "0.1.5"
chrono = "0.2.17"
log = "0.3.5"
env_logger = "0.3.2"
